"""Commit

Revision ID: 1a6eb5195217
Revises: 18c84453f409
Create Date: 2023-11-17 13:55:17.635851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6eb5195217'
down_revision: Union[str, None] = '18c84453f409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('date_from', sa.Date(), nullable=False))
    op.add_column('bookings', sa.Column('date_to', sa.Date(), nullable=False))
    op.drop_column('bookings', 'data_from')
    op.drop_column('bookings', 'data_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('data_to', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('data_from', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'date_to')
    op.drop_column('bookings', 'date_from')
    # ### end Alembic commands ###
